version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest' #最新版npm
    restart: unless-stopped
    ports:
      - '1088:80'
      - '1089:81'
      - '1090:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  maccms10:
      volumes:
          - ./mnt/maccms:/data
          - ./mnt/maccms/template:/opt/maccms10/template
      ports:
          - '7878:7878'
      image: gs0245/maccms10
        #network_mode: host (optional)
      restart: always
